### PR TITLE
2 2 api

### PR DESCRIPTION
**Pull request by jubiiz**
# To test: 
## All 9 tests pass.
```./gradlew test -i```

## smoke test:
Run the app: 
```
./gradlew bootRun
```

### need to somehow get a todoItem record in your database
I did it from the docker cli: 
* Open docker desktop
* Go to exec tab 
* run the comands:  (PASSWORD IS lala)
```
mysql -u root -p
USE dev;
INSERT INTO todo_item (id, name, status, description) VALUES (1, "Buy Milk", 1, "something");
```

### Update status: 
Using postman or similar, send the following url as PUT (NOT post!!!) with empty body: 
```
http://localhost:8080/todoItem/updateStatus?id=1&status=DONE
```

### Get an item: 
use postman or similar.
```
http://localhost:8080/todoItem/1
```

### CODE REVIEW

**Comment by wangwiza** [comment]
I believe that build artifacts such as the `build` folder shouldn't be included in version control, unless this is intentional.

**Review by wangwiza — CHANGES_REQUESTED** [review]
Should build artifacts such as `.class` files (or anything in the `build` folder) be included in version control? Not really a request for change, but something to ponder before completing the PR

**Comment by jubiiz** [comment]
@wangwiza Good point. Removed.

**Review by vladarama — APPROVED** [review]
LGTM 👍

**Pull request merged**
